import test from 'node:test';
import assert from 'node:assert/strict';
import { LocalEgyptVipPartnerAdapter } from '../lib/travel/vip/local-partner';
import { InMemoryVipRepository } from '../lib/travel/vip/repository';
import { syntheticVipPartnerConfig, validateVipPartnerConfig } from '../lib/travel/vip/config';
import type { VipPartnerConfig } from '../lib/travel/contracts';
import { readFileSync } from 'node:fs';

const now = new Date('2026-08-25T10:00:00.000Z');
const future = '2026-08-27T12:00:00.000Z';
function setup(config: VipPartnerConfig = syntheticVipPartnerConfig, options = {}) { const repository = new InMemoryVipRepository(config); return { repository, adapter: new LocalEgyptVipPartnerAdapter(repository, { now: () => now, ...options }) }; }
async function quote(adapter: LocalEgyptVipPartnerAdapter, location = 'Cairo') { const search = await adapter.searchVipServices({ cityOrLocation: location, dateTime: future, passengerCount: 2 }); return adapter.getVipQuote(search.offers[0].id); }
test.beforeEach(() => { process.env.VIP_LOCAL_ENV = 'local_test'; delete process.env.VIP_LOCAL_PRODUCTION_ENABLED; delete process.env.NEXT_PUBLIC_VIP_LOCAL_KEY; });
test.after(() => { delete process.env.VIP_LOCAL_ENV; });

test('search returns only existing DIR3 VIP category and synthetic markers', async () => { const { adapter } = setup(); const result = await adapter.searchVipServices({ cityOrLocation: 'Cairo', dateTime: future, passengerCount: 2 }); assert.equal(result.status, 'ok'); assert.equal(result.offers[0].serviceType, 'DIR3 VIP'); assert.equal(result.offers[0].source, 'synthetic_test_placeholder'); assert.equal(result.offers[0].verificationStatus, 'UNVERIFIED'); });
test('coverage includes representative Egypt test locations', async () => { const { adapter } = setup(); for (const city of syntheticVipPartnerConfig.coverage) assert.equal((await adapter.searchVipServices({ cityOrLocation: city, dateTime: future, passengerCount: 1 })).status, 'ok'); });
test('invalid coverage returns no results', async () => { const { adapter } = setup(); assert.equal((await adapter.searchVipServices({ cityOrLocation: 'London', dateTime: future, passengerCount: 1 })).status, 'no_results'); });
test('invalid and insufficient-lead-time dates are safe', async () => { const { adapter } = setup(); await assert.rejects(() => adapter.searchVipServices({ cityOrLocation: 'Cairo', dateTime: 'bad', passengerCount: 1 }), /INVALID_VIP_DATE/); assert.equal((await adapter.searchVipServices({ cityOrLocation: 'Cairo', dateTime: '2026-08-25T12:00:00Z', passengerCount: 1 })).status, 'no_results'); });
test('missing fields and unsupported service fail validation', async () => { const { adapter } = setup(); await assert.rejects(() => adapter.searchVipServices({ cityOrLocation: '', dateTime: future, passengerCount: 0 }), /INVALID_VIP_REQUEST/); await assert.rejects(() => adapter.searchVipServices({ cityOrLocation: 'Cairo', dateTime: future, passengerCount: 1, serviceType: 'bad' as 'DIR3 VIP' }), /UNSUPPORTED_VIP_SERVICE/); });
test('quote and unchanged revalidation work', async () => { const { adapter } = setup(); const original = await quote(adapter); const refreshed = await adapter.revalidateVipQuote(original.quoteId); assert.equal(refreshed.changed, false); assert.equal(refreshed.price, original.price); });
test('pricing change is explicit during revalidation', async () => { const { adapter } = setup(syntheticVipPartnerConfig, { simulatePriceChange: true }); const original = await quote(adapter); const refreshed = await adapter.revalidateVipQuote(original.quoteId); assert.equal(refreshed.changed, true); assert.equal(refreshed.version, 2); assert.notEqual(refreshed.price, original.price); });
test('booking request and duplicate call are idempotent', async () => { const { adapter } = setup(); const q = await quote(adapter); const input = { quoteId: q.quoteId, customerMetadata: { customerId: 'test-customer' }, idempotencyKey: 'same-request' }; const first = await adapter.createVipBooking(input); assert.deepEqual(await adapter.createVipBooking(input), first); assert.equal(first.status, 'pending_partner_review'); });
test('missing idempotency key fails closed', async () => { const { adapter } = setup(); const q = await quote(adapter); await assert.rejects(() => adapter.createVipBooking({ quoteId: q.quoteId, customerMetadata: {}, idempotencyKey: '' }), /VIP_IDEMPOTENCY_REQUIRED/); });
test('partner confirmation and cancellation complete local workflow', async () => { const { adapter } = setup(); const q = await quote(adapter); const booking = await adapter.createVipBooking({ quoteId: q.quoteId, customerMetadata: {}, idempotencyKey: 'confirm-cancel' }); const confirmed = await adapter.confirmVipBooking(booking.bookingReference, 'TEST-CONFIRMATION'); assert.equal(confirmed.status, 'confirmed'); const cancelled = await adapter.cancelVipBooking(booking.bookingReference, 'test cancellation'); assert.equal(cancelled.status, 'cancelled'); assert.deepEqual(await adapter.cancelVipBooking(booking.bookingReference, 'safe retry'), cancelled); });
test('failed confirmation is handled', async () => { const { adapter } = setup(); const q = await quote(adapter); const booking = await adapter.createVipBooking({ quoteId: q.quoteId, customerMetadata: {}, idempotencyKey: 'failed-confirm' }); await assert.rejects(() => adapter.confirmVipBooking(booking.bookingReference, ''), /VIP_CONFIRMATION_FAILED/); });
test('timeout/no-response state is retry-safe', async () => { const { adapter } = setup(syntheticVipPartnerConfig, { simulateNoResponse: true }); const q = await quote(adapter); const input = { quoteId: q.quoteId, customerMetadata: {}, idempotencyKey: 'timeout-case' }; const first = await adapter.createVipBooking(input); assert.equal(first.status, 'no_response'); assert.deepEqual(await adapter.createVipBooking(input), first); });
test('inactive partner blocks discovery and booking', async () => { const inactive = { ...syntheticVipPartnerConfig, status: 'INACTIVE' as const }; const { adapter, repository } = setup(inactive); assert.equal((await adapter.searchVipServices({ cityOrLocation: 'Cairo', dateTime: future, passengerCount: 1 })).status, 'blocked'); const activeAdapter = new LocalEgyptVipPartnerAdapter(repository, { now: () => now }); await repository.saveConfig(syntheticVipPartnerConfig); const q = await quote(activeAdapter); await repository.saveConfig(inactive); await assert.rejects(() => activeAdapter.createVipBooking({ quoteId: q.quoteId, customerMetadata: {}, idempotencyKey: 'inactive' }), /VIP_PARTNER_INACTIVE/); });
test('malformed partner data blocks provider status', async () => { const malformed = { ...syntheticVipPartnerConfig, coverage: [] }; const { adapter } = setup(malformed); assert.equal((await adapter.getVipProviderStatus()).status, 'blocked'); assert.throws(() => validateVipPartnerConfig(malformed), /MALFORMED/); });
test('audit trail records full workflow', async () => { const { adapter, repository } = setup(); const q = await quote(adapter); const b = await adapter.createVipBooking({ quoteId: q.quoteId, customerMetadata: {}, idempotencyKey: 'audit' }); await adapter.confirmVipBooking(b.bookingReference, 'TEST'); await adapter.cancelVipBooking(b.bookingReference, 'TEST'); assert.deepEqual(repository.getAuditTrail().map((event) => event.event), ['vip.search.offer_created', 'vip.quote.created', 'vip.booking.requested', 'vip.booking.confirmed', 'vip.booking.cancelled']); });
test('production and public config signals forbid mutations', async () => { const { adapter } = setup(); const q = await quote(adapter); process.env.VIP_LOCAL_PRODUCTION_ENABLED = 'true'; await assert.rejects(() => adapter.createVipBooking({ quoteId: q.quoteId, customerMetadata: {}, idempotencyKey: 'prod-block' }), /VIP_LOCAL_TEST_MODE_REQUIRED/); delete process.env.VIP_LOCAL_PRODUCTION_ENABLED; process.env.NEXT_PUBLIC_VIP_LOCAL_KEY = 'forbidden'; await assert.rejects(() => adapter.createVipBooking({ quoteId: q.quoteId, customerMetadata: {}, idempotencyKey: 'public-block' }), /VIP_LOCAL_TEST_MODE_REQUIRED/); });
test('synthetic fixture contains no credential or verified claim', () => { const serialized = JSON.stringify(syntheticVipPartnerConfig); assert.equal(/password|secret|api.?key|@/i.test(serialized), false); assert.equal(serialized.includes('partner_verified'), false); assert.equal(syntheticVipPartnerConfig.verificationStatus, 'UNVERIFIED'); });
test('admin form exposes every partner-replaceable operational field', () => {
  const form = readFileSync(new URL('../components/admin/VipPartnerConfigForm.tsx', import.meta.url), 'utf8');
  for (const field of ['legalName', 'displayName', 'coverage', 'operatingHours', 'responseSlaMinutes', 'bookingMethod', 'pricingModel', 'basePrice', 'perPassengerPrice', 'taxAndFees', 'cancellationPolicy', 'amendmentPolicy', 'quoteValidityMinutes', 'minimumLeadTimeHours', 'settlementModel', 'operationalContact', 'escalationContact', 'status']) assert.match(form, new RegExp(`name=["']${field}["']`));
  assert.match(form, /UNVERIFIED \/ TEST DATA/);
});
