export type TravelLanguage = 'ar' | 'en';
export type TravelCapability = 'fly' | 'stay' | 'drive' | 'concierge' | 'vip';

export type TravelParty = { adults: number; children: number; childAges?: number[] };
export type TravelPreferences = {
  hotelClass?: number;
  cabin?: string;
  seat?: string;
  carType?: string;
  pace?: 'relaxed' | 'balanced' | 'busy';
  familyFriendly?: boolean;
  dietaryNotes?: string[];
  accessibilityNotes?: string[];
};
export type TravelIntent = {
  language: TravelLanguage;
  kind: 'new_trip' | 'modify_trip' | 'compare' | 'human_handoff' | 'unknown';
  origin?: string;
  destination?: string;
  startDate?: string;
  endDate?: string;
  dateText?: string;
  flexibility?: string;
  travelers?: TravelParty;
  budget?: number;
  currency?: string;
  preferences: TravelPreferences;
  requestedCapabilities: TravelCapability[];
  constraints: string[];
  modifications: Array<{ field: string; value: string | number | boolean }>;
  missingRequired: string[];
  confidence: number;
};
export type TravelMemoryRecord = {
  ownerId: string;
  tenantId: string;
  sessionId: string;
  revision: number;
  preferences: TravelPreferences;
  preferredCities: string[];
  budgetTendency?: 'value' | 'balanced' | 'premium';
  travelParty?: TravelParty;
  currentPlanId?: string;
  createdAt: string;
  updatedAt: string;
};
export type TripPlanStatus = 'draft' | 'searching' | 'options_ready' | 'awaiting_confirmation' | 'partially_blocked' | 'confirmed' | 'cancelled';
export type TripApprovalState = 'NOT_REQUESTED' | 'PROPOSED' | 'READY_FOR_CONFIRMATION' | 'CONFIRMED_BY_USER';
export type TripSegment = { id: string; origin?: string; destination: string; startDate?: string; endDate?: string };
export type NormalizedTravelOption = {
  id: string;
  capability: TravelCapability;
  title: string;
  currency?: string;
  amount?: string;
  durationMinutes?: number;
  distanceMeters?: number;
  refundable?: boolean;
  familyFriendly?: boolean;
  premium?: boolean;
  evidence: string[];
  providerReference: string;
  expiresAt?: string;
  metadata: Record<string, string | number | boolean | undefined>;
};
export type TripServicePlan = {
  capability: TravelCapability;
  status: 'pending' | 'available' | 'no_results' | 'blocked' | 'unavailable' | 'selected' | 'removed';
  options: NormalizedTravelOption[];
  selectedOptionId?: string;
  userMessage?: string;
  blockedReason?: 'vendor_access' | 'entitlement' | 'test_data_only' | 'provider_unavailable';
};
export type TripPlan = {
  id: string;
  ownerId: string;
  tenantId: string;
  revision: number;
  language: TravelLanguage;
  destination?: string;
  travelers: TravelParty;
  segments: TripSegment[];
  services: TripServicePlan[];
  budget?: { amount: number; currency: string };
  estimatedTotal?: { amount: string; currency: string; complete: boolean };
  status: TripPlanStatus;
  approvalState: TripApprovalState;
  createdAt: string;
  updatedAt: string;
};
export type CapabilitySearchContext = { ownerId: string; tenantId: string; plan: TripPlan; intent: TravelIntent; signal?: AbortSignal };
export type CapabilitySearchResult = {
  capability: TravelCapability;
  status: TripServicePlan['status'];
  options: NormalizedTravelOption[];
  blockedReason?: TripServicePlan['blockedReason'];
  userMessage?: string;
};
export type TravelCapabilityAdapter = {
  capability: TravelCapability;
  search(context: CapabilitySearchContext): Promise<CapabilitySearchResult>;
  revalidate?(option: NormalizedTravelOption, context: CapabilitySearchContext): Promise<NormalizedTravelOption>;
};
export type OrchestrationResult = { intent: TravelIntent; plan: TripPlan; handoff?: HumanHandoff };
export type ActionState = 'PROPOSED' | 'READY_FOR_CONFIRMATION' | 'CONFIRMED_BY_USER' | 'EXECUTING' | 'CONFIRMED' | 'FAILED' | 'CANCELLED';
export type TravelAction = {
  id: string;
  ownerId: string;
  tenantId: string;
  planId: string;
  capability: TravelCapability | 'payment';
  kind: 'book' | 'cancel' | 'modify' | 'charge';
  state: ActionState;
  idempotencyKey: string;
  confirmationNonce: string;
  createdAt: string;
  updatedAt: string;
  sanitizedError?: string;
};
export type GuardianEvent = {
  id: string;
  ownerId: string;
  tenantId: string;
  planId: string;
  type: 'flight_change' | 'booking_change' | 'provider_notification' | 'trip_milestone' | 'service_issue';
  occurredAt: string;
  source: 'provider_webhook' | 'internal_schedule' | 'manual' | 'test';
  verified: boolean;
  summary: string;
};
export type GuardianGuidance = { eventId: string; severity: 'info' | 'attention' | 'urgent'; message: string; liveMonitoringActive: false; suggestedActions: string[] };
export type HumanHandoff = {
  id: string;
  ownerId: string;
  tenantId: string;
  planId?: string;
  reason: 'provider_blocked' | 'booking_failed' | 'manual_partner_action' | 'customer_requested' | 'low_confidence' | 'exceptional_request';
  status: 'requested' | 'queued' | 'resolved';
  context: { destination?: string; dates?: string; travelers?: TravelParty; requestedCapabilities: TravelCapability[]; blockedCapabilities: TravelCapability[] };
  createdAt: string;
};
