-- Task #167. Coordinated catalogue/data release, NOT applied to Production by this file.
-- Generated by scripts/generate-drive-september27-sql.mjs from the same customer catalogue.
-- No changes to products, partners, existing requests, quotes, bookings or payments.
BEGIN;
SET LOCAL lock_timeout='5s';
SET LOCAL statement_timeout='30s';

ALTER TABLE public.drive_managed_offers DROP CONSTRAINT drive_managed_offers_supplier_source_check;
ALTER TABLE public.drive_managed_offers ADD CONSTRAINT drive_managed_offers_supplier_source_check
 CHECK(supplier_source IN ('safeerat-al-arab','egypt-operations'));
ALTER TABLE public.drive_managed_offers ADD COLUMN daily_period_hours integer
 CHECK(daily_period_hours IS NULL OR daily_period_hours=24);

-- Fail before overwriting an independently edited rate. Six unmatched legacy offers stay intact.
DO $$ BEGIN
 IF (SELECT count(*) FROM public.drive_managed_offers o JOIN
  (VALUES ('safeerat-eg-jetour-t2',50::numeric,100::numeric,'USD'),
   ('safeerat-eg-jetour-x90',1500,3500,'EGP'),('safeerat-eg-nissan-sunny',900,1800,'EGP'))
  expected(id,airport,daily,currency) ON o.id=expected.id
  WHERE o.version='safeerat-eg-20260916-v1' AND o.active AND o.supplier_source='safeerat-al-arab'
   AND o.airport_amount=expected.airport AND o.daily_amount=expected.daily
   AND o.supplier_currency=expected.currency) <> 3 THEN
  RAISE EXCEPTION 'CATALOG_BASELINE_CHANGED';
 END IF;
 IF EXISTS(SELECT 1 FROM public.drive_managed_offers WHERE id IN
  ('managed-eg-mercedes-v250','managed-eg-mercedes-v300','managed-eg-kia-sportage','managed-eg-hyundai-accent','managed-eg-jetour-x70','managed-eg-soueast-s05','managed-eg-soueast-s09','managed-eg-soueast-s07','managed-eg-range-rover-sport','managed-eg-toyota-land-cruiser','managed-eg-cadillac-escalade')) THEN
  RAISE EXCEPTION 'NEW_OFFER_ID_ALREADY_EXISTS';
 END IF;
END $$;

INSERT INTO public.drive_managed_offers(id,vehicle_id,country,supplier_source,airport_amount,daily_amount,supplier_currency,version,daily_period_hours)
SELECT v.id,v.vehicle,'EG','egypt-operations',v.airport,v.daily,'USD','managed-eg-20260927-v1',24
FROM (VALUES
('managed-eg-mercedes-v250','mercedes-v250',137.50,275.00),
('managed-eg-mercedes-v300','mercedes-v300',220.00,440.00),
('managed-eg-kia-sportage','kia-sportage',66.00,132.00),
('managed-eg-hyundai-accent','hyundai-accent',33.00,66.00),
('safeerat-eg-jetour-t2','jetour-t2',82.50,165.00),
('managed-eg-jetour-x70','jetour-x70',44.00,88.00),
('safeerat-eg-jetour-x90','jetour-x90',55.00,110.00),
('managed-eg-soueast-s05','soueast-s05',44.00,88.00),
('managed-eg-soueast-s09','soueast-s09',55.00,110.00),
('managed-eg-soueast-s07','soueast-s07',44.00,88.00),
('managed-eg-range-rover-sport','range-rover-sport',330.00,660.00),
('safeerat-eg-nissan-sunny','nissan-sunny',33.00,66.00),
('managed-eg-toyota-land-cruiser','toyota-land-cruiser',247.50,495.00),
('managed-eg-cadillac-escalade','cadillac-escalade',550.00,1100.00)
) AS v(id,vehicle,airport,daily)
ON CONFLICT(id) DO UPDATE SET airport_amount=excluded.airport_amount,daily_amount=excluded.daily_amount,
 supplier_currency=excluded.supplier_currency,supplier_source=excluded.supplier_source,
 version=excluded.version,daily_period_hours=excluded.daily_period_hours;

-- Separate version argument leaves trip payload/idempotent retry equality unchanged.
DROP FUNCTION public.create_managed_drive_request(text,text,jsonb);
CREATE OR REPLACE FUNCTION public.create_managed_drive_request(p_offer_id text,p_key text,p_trip jsonb,p_catalog_version text DEFAULT NULL)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE v_offer public.drive_managed_offers%ROWTYPE; v_request public.marketplace_requests%ROWTYPE;
 v_pickup timestamptz; v_return timestamptz; v_arrival timestamptz; v_amount numeric; v_reference text; v_email text;
BEGIN
 IF auth.uid() IS NULL OR current_setting('role',true) IS DISTINCT FROM 'authenticated' THEN RAISE EXCEPTION 'AUTH_REQUIRED' USING ERRCODE='42501'; END IF;
 SELECT email INTO v_email FROM public.profiles WHERE id=auth.uid() AND status='active' AND deleted_at IS NULL;
 IF NOT FOUND THEN RAISE EXCEPTION 'AUTH_REQUIRED' USING ERRCODE='42501'; END IF;
 IF p_key IS NULL OR p_key !~ '^[A-Za-z0-9:_-]{16,120}$' OR p_trip IS NULL OR jsonb_typeof(p_trip)<>'object' OR octet_length(p_trip::text)>8000 THEN RAISE EXCEPTION 'INVALID_REQUEST' USING ERRCODE='22023'; END IF;
 v_reference := 'REQ-'||upper(substr(md5(auth.uid()::text||':'||p_key),1,20));
 PERFORM pg_advisory_xact_lock(hashtextextended(v_reference,0));
 SELECT * INTO v_request FROM public.marketplace_requests WHERE request_reference=v_reference AND user_id=auth.uid();
 IF FOUND THEN
  IF v_request.drive_offer_id IS DISTINCT FROM p_offer_id OR NOT EXISTS (SELECT 1 FROM public.drive_request_context WHERE request_id=v_request.id AND trip=p_trip) THEN RAISE EXCEPTION 'IDEMPOTENCY_CONFLICT' USING ERRCODE='23505'; END IF;
  RETURN jsonb_build_object('reference',v_request.request_reference,'status',v_request.status,'replayed',true);
 END IF;
 SELECT * INTO v_offer FROM public.drive_managed_offers WHERE id=p_offer_id AND active FOR SHARE;
 IF NOT FOUND THEN RAISE EXCEPTION 'OFFER_UNAVAILABLE' USING ERRCODE='22023'; END IF;
 IF (p_trip->>'mode') IS NULL OR p_trip->>'mode' NOT IN ('airport','chauffeur')
   OR coalesce(length(btrim(p_trip->>'pickup')),0) NOT BETWEEN 2 AND 200
   OR coalesce(length(btrim(p_trip->>'dropoff')),0) NOT BETWEEN 2 AND 200
   OR coalesce(length(btrim(p_trip->>'name')),0) NOT BETWEEN 2 AND 120
   OR coalesce(length(btrim(p_trip->>'phone')),0) NOT BETWEEN 7 AND 30
   OR coalesce(p_trip->>'phone','') !~ '^[+0-9 ()-]{7,30}$'
   OR p_trip->'acknowledged' IS DISTINCT FROM 'true'::jsonb
   OR coalesce(p_trip->>'currency','') NOT IN ('EGP','USD','SAR','EUR','AED')
   OR coalesce(p_trip->>'minimumModelYear','') <> '2025'
   OR p_trip->'acceptableModelYears' IS DISTINCT FROM '[2025,2026,2027]'::jsonb
   OR coalesce(length(p_trip->>'notes'),0)>1000
   OR coalesce(length(p_trip->>'specialRequest'),0)>500
   OR coalesce(p_trip->>'passengers','') !~ '^([1-9]|1[0-9]|20)$'
   OR coalesce(p_trip->>'luggage','') !~ '^([0-9]|1[0-9]|20)$'
   OR coalesce(p_trip->>'pickupAt','') !~ '^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$'
   OR coalesce(p_trip->>'returnAt','') !~ '^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$'
   THEN RAISE EXCEPTION 'INVALID_TRIP' USING ERRCODE='22023'; END IF;
 v_pickup := (p_trip->>'pickupAt')::timestamp AT TIME ZONE 'Africa/Cairo';
 v_return := (p_trip->>'returnAt')::timestamp AT TIME ZONE 'Africa/Cairo';
 IF to_char(v_pickup AT TIME ZONE 'Africa/Cairo','YYYY-MM-DD"T"HH24:MI')<>p_trip->>'pickupAt'
   OR to_char(v_return AT TIME ZONE 'Africa/Cairo','YYYY-MM-DD"T"HH24:MI')<>p_trip->>'returnAt'
   OR (v_pickup-interval '1 hour') AT TIME ZONE 'Africa/Cairo'=v_pickup AT TIME ZONE 'Africa/Cairo'
   OR (v_return-interval '1 hour') AT TIME ZONE 'Africa/Cairo'=v_return AT TIME ZONE 'Africa/Cairo'
   OR v_pickup<now()+interval '6 hours' OR v_return<=v_pickup OR v_return>v_pickup+interval '90 days'
   THEN RAISE EXCEPTION 'INVALID_PICKUP_RETURN_TIME' USING ERRCODE='22023'; END IF;
 IF p_trip->>'mode'='airport' THEN
  IF coalesce(p_trip->>'flightNumber','') !~ '^[A-Za-z0-9 -]{2,20}$' OR coalesce(p_trip->>'flightArrival','') !~ '^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$' THEN RAISE EXCEPTION 'FLIGHT_DETAILS_REQUIRED' USING ERRCODE='22023'; END IF;
  v_arrival := (p_trip->>'flightArrival')::timestamp AT TIME ZONE 'Africa/Cairo';
  IF to_char(v_arrival AT TIME ZONE 'Africa/Cairo','YYYY-MM-DD"T"HH24:MI')<>p_trip->>'flightArrival'
    OR (v_arrival-interval '1 hour') AT TIME ZONE 'Africa/Cairo'=v_arrival AT TIME ZONE 'Africa/Cairo'
    THEN RAISE EXCEPTION 'INVALID_FLIGHT_TIME' USING ERRCODE='22023'; END IF;
 END IF;
 -- Replay already returned above: old REQs remain recoverable across a catalogue release.
 IF coalesce(p_catalog_version,'safeerat-eg-20260916-v1') IS DISTINCT FROM v_offer.version THEN
  RAISE EXCEPTION 'CATALOG_CHANGED' USING ERRCODE='40001';
 END IF;
 v_amount:=CASE WHEN p_trip->>'mode'='airport' THEN v_offer.airport_amount ELSE v_offer.daily_amount END;
 IF v_amount IS NULL THEN RAISE EXCEPTION 'RATE_UNAVAILABLE' USING ERRCODE='22023'; END IF;
 INSERT INTO public.marketplace_requests (request_reference,user_id,drive_offer_id,request_type,requested_for,traveller_count,customer_brief,marketplace_family,supplier_name,service_name,next_action)
 VALUES (v_reference,auth.uid(),v_offer.id,'request_to_confirm',v_pickup,(p_trip->>'passengers')::int,
 jsonb_build_object('email',v_email,'name',p_trip->>'name','phone',p_trip->>'phone'),'drive',CASE WHEN v_offer.supplier_source='egypt-operations' THEN 'Egypt Operations' ELSE 'Safeerat Al Arab Cars' END,v_offer.vehicle_id,'egypt_operations_review') RETURNING * INTO v_request;
 INSERT INTO public.drive_request_context (request_id,country,offer_version,supplier_amount,supplier_currency,trip) VALUES (v_request.id,v_offer.country,v_offer.version,v_amount,v_offer.supplier_currency,p_trip);
 INSERT INTO public.drive_request_events(request_id,actor_user_id,country,action,new_status)
 VALUES(v_request.id,auth.uid(),'EG','created','request_submitted');
 RETURN jsonb_build_object('reference',v_reference,'status',v_request.status,'replayed',false);
END $$;
REVOKE ALL ON FUNCTION public.create_managed_drive_request(text,text,jsonb,text) FROM PUBLIC,anon,service_role;
GRANT EXECUTE ON FUNCTION public.create_managed_drive_request(text,text,jsonb,text) TO authenticated;


NOTIFY pgrst,'reload schema';
COMMIT;
