import { TravelProviderError } from "../errors"; import type { ActivityDetails, ActivityDestination, ActivityPricing, ActivitySearchResult, ActivitySummary, ActivityTaxonomy, ActivityAvailabilitySchedule } from "../contracts";
const text=(v: unknown)=>typeof v === "string" || typeof v === "number" ? String(v) : undefined;
export const aliases: Record<string,string[]> = { riyadh: ["riyadh"], "الرياض": ["riyadh"], jeddah: ["jeddah"], "جدة": ["jeddah"], alula: ["alula", "al ula", "al-ula"], "العلا": ["alula"], cairo: ["cairo"], "القاهرة": ["cairo"], giza: ["giza"], "الجيزة": ["giza"], "sharm el sheikh": ["sharm el sheikh", "sharm el-sheikh"], "شرم الشيخ": ["sharm el sheikh"], hurghada: ["hurghada"], "الغردقة": ["hurghada"] };
export function resolveDestinationName(value: string) { const key=value.trim().toLowerCase(); return aliases[key]?.[0] || (key.replace(/[-_]+/g, " ") === "al ula" ? "alula" : key); }
export function mapDestination(raw: unknown): ActivityDestination { const item=raw as Record<string,unknown>; const id=text(item.destinationId)||text(item.id); const name=text(item.destinationName)||text(item.name); if(!id||!name) throw new TravelProviderError("INVALID_PROVIDER_RESPONSE","Viator returned an invalid destination."); return {id,name,country:text(item.country),aliases:aliases[name.toLowerCase()]||[name.toLowerCase()]}; }
export function mapTaxonomy(raw: unknown): ActivityTaxonomy { const item=raw as Record<string,unknown>; const id=text(item.id)||text(item.tagId); const name=text(item.name)||text(item.tagName); if(!id||!name) throw new TravelProviderError("INVALID_PROVIDER_RESPONSE","Viator returned invalid taxonomy."); return {id,name,parentId:text(item.parentId)}; }
export function mapSummary(raw: unknown): ActivitySummary { const item=raw as Record<string,unknown>; const productCode=text(item.productCode)||text(item.id); const title=text(item.title)||text(item.name); if(!productCode||!title) throw new TravelProviderError("INVALID_PROVIDER_RESPONSE","Viator returned an invalid product."); const destination=mapDestination(item.destination||{id:text(item.destinationId)||"unknown",name:text(item.destinationName)||"Unknown"}); return {productCode,title,shortDescription:text(item.shortDescription),destination,images:Array.isArray(item.images)?item.images.filter((v):v is string=>typeof v === "string"):[],rating:typeof item.rating === "number"?item.rating:undefined,reviewCount:typeof item.reviewCount === "number"?item.reviewCount:undefined,currency:text(item.currency),fromPrice:text(item.fromPrice),duration:text(item.duration),tags:Array.isArray(item.tags)?item.tags.filter((v):v is string=>typeof v === "string"):[],cancellationSummary:text(item.cancellationSummary),affiliateUrl:text(item.affiliateUrl)}; }
export function mapDetails(raw: unknown): ActivityDetails { const item=raw as Record<string,unknown>; return {...mapSummary(raw),description:text(item.description),itinerary:Array.isArray(item.itinerary)?item.itinerary.filter((v):v is string=>typeof v === "string"):[],inclusions:Array.isArray(item.inclusions)?item.inclusions.filter((v):v is string=>typeof v === "string"):[],exclusions:Array.isArray(item.exclusions)?item.exclusions.filter((v):v is string=>typeof v === "string"):[],additionalInfo:Array.isArray(item.additionalInfo)?item.additionalInfo.filter((v):v is string=>typeof v === "string"):[],meetingPoint:text(item.meetingPoint),pickupDetails:text(item.pickupDetails),language:text(item.language),cancellationPolicy:text(item.cancellationPolicy),options:Array.isArray(item.options)?item.options.filter((v):v is string=>typeof v === "string"):[]}; }
export function mapPricing(raw: unknown): ActivityPricing { const item=raw as Record<string,unknown>; return {pricingPackageType:text(item.pricingPackageType),unitType:text(item.unitType),minTravelers:typeof item.minTravelers === "number"?item.minTravelers:undefined,maxTravelers:typeof item.maxTravelers === "number"?item.maxTravelers:undefined,ageBand:text(item.ageBand),currency:text(item.currency)||"USD",amount:text(item.amount)||text(item.price)||"0"}; }
export function mapSchedule(raw: unknown): ActivityAvailabilitySchedule { const item=raw as Record<string,unknown>; const productCode=text(item.productCode)||text(item.id); if(!productCode) throw new TravelProviderError("INVALID_PROVIDER_RESPONSE","Viator returned an invalid schedule."); const records=Array.isArray(item.pricingRecords)?item.pricingRecords.map(mapPricing):[]; return {productCode,seasons:Array.isArray(item.seasons)?item.seasons.filter((v):v is string=>typeof v === "string"):[],daysOfWeek:Array.isArray(item.daysOfWeek)?item.daysOfWeek.filter((v):v is string=>typeof v === "string"):[],unavailableDates:Array.isArray(item.unavailableDates)?item.unavailableDates.filter((v):v is string=>typeof v === "string"):[],productOptionCode:text(item.productOptionCode),startTimes:Array.isArray(item.startTimes)?item.startTimes.filter((v):v is string=>typeof v === "string"):[],pricingRecords:records}; }
export function mapSearch(raw: unknown): ActivitySearchResult { const items=(raw as {products?:unknown[];data?:{products?:unknown[]}})?.products || (raw as {data?:{products?:unknown[]}})?.data?.products || []; const activities=Array.isArray(items)?items.map(mapSummary):[]; return {provider:"viator",status:activities.length?"ok":"no_results",activities,...(activities.length?{}:{error:{code:"NO_RESULTS",message:"No activities matched the request.",retryable:false}})}; }